# Generated by Django 4.0.2 on 2022-02-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registry',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
