# Generated by Django 4.0.2 on 2022-02-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_registry_first_name_registry_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='name',
            field=models.CharField(default='dinner', max_length=50),
        ),
        migrations.AlterField(
            model_name='registry',
            name='meal',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=50),
        ),
    ]
