# Generated by Django 4.0.2 on 2022-02-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_dinner_name_alter_registry_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='image',
            new_name='image_url',
        ),
    ]
