# Generated by Django 4.0.2 on 2022-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_image_registry_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='cashier',
            field=models.CharField(default='Abdelaali ES SALMI', max_length=150),
            preserve_default=False,
        ),
    ]
