# Generated by Django 4.0.2 on 2022-02-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_registry_cashier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default='benguerir', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
