# Generated by Django 4.0.2 on 2022-08-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('staff', 'staff'), ('student', 'student'), ('pooler', 'pooler'), ('prestataire', 'prestataire')], max_length=50)),
                ('authorized', models.BooleanField(default=True)),
                ('superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
