# Generated by Django 4.0.2 on 2022-08-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='badge',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
