# Generated by Django 4.0.2 on 2023-03-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_id', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('Not found', 'Not found'), ('Not authorized', 'Not authorized'), ('Already badged', 'Already badged')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
