# Generated by Django 4.0.2 on 2023-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_logs_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='limit',
            field=models.IntegerField(default=1),
        ),
    ]
