# Generated by Django 4.0.2 on 2023-04-22 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_person_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='limit',
        ),
    ]
