# Generated by Django 4.0.2 on 2023-04-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_remove_person_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='limit',
            field=models.IntegerField(default=1),
        ),
    ]
