# Generated by Django 4.0.2 on 2023-04-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_person_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='kind',
            field=models.CharField(choices=[('Not found', 'Not found'), ('Not authorized', 'Not authorized'), ('Already badged', 'Already badged'), ('Limit reached', 'Limit reached')], max_length=50),
        ),
    ]
